# Generated by Django 4.2.7 on 2023-11-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanlinessLevel',
            fields=[
                ('cleanliness_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('cleanliness_level_name', models.TextField(max_length=255)),
                ('standard', models.TextField(max_length=255)),
                ('nvr_limit', models.FloatField()),
                ('range_1_count_limit', models.IntegerField()),
                ('range_2_count_limit', models.IntegerField()),
                ('range_3_count_limit', models.IntegerField()),
                ('range_4_count_limit', models.IntegerField()),
                ('range_5_count_limit', models.IntegerField()),
                ('range_1_size_limit', models.IntegerField()),
                ('range_2_size_limit', models.IntegerField()),
                ('range_3_size_limit', models.IntegerField()),
                ('range_4_size_limit', models.IntegerField()),
                ('range_5_size_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contaminants',
            fields=[
                ('contaminant_id', models.AutoField(primary_key=True, serialize=False)),
                ('particulate_bool', models.BooleanField(default=False)),
                ('liquid_bool', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damage_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('mars_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('requires_bubble_point', models.BooleanField()),
                ('item_type', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('in_commission', models.BooleanField(default=True)),
                ('cleanliness_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cleanlinesslevel')),
            ],
        ),
        migrations.CreateModel(
            name='LabLog',
            fields=[
                ('lab_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('range_1_count', models.IntegerField()),
                ('range_2_count', models.IntegerField()),
                ('range_3_count', models.IntegerField()),
                ('range_4_count', models.IntegerField()),
                ('range_5_count', models.IntegerField()),
                ('cleanliness_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cleanlinesslevel')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('acid_compatible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='workorder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('need_by_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=500)),
                ('cleanliness_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cleanlinesslevel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('work_order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('contaminant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.contaminants')),
                ('damage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.damage')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='LabLogItem',
            fields=[
                ('lab_log_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('lab_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lablog')),
            ],
        ),
        migrations.AddField(
            model_name='lablog',
            name='items',
            field=models.ManyToManyField(through='inventory.LabLogItem', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material'),
        ),
        migrations.CreateModel(
            name='BubblePointLog',
            fields=[
                ('bubble_point_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('bubble_one', models.FloatField()),
                ('bubble_two', models.FloatField()),
                ('bubble_three', models.FloatField()),
                ('bubble_four', models.FloatField()),
                ('average_bubble', models.FloatField()),
                ('bubble_point', models.FloatField()),
                ('pass_fail', models.BooleanField()),
                ('mars_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
            ],
        ),
    ]
