# Generated by Django 4.2.7 on 2023-11-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contaminants',
            new_name='Contaminant',
        ),
    ]
