# Generated by Django 4.2.7 on 2023-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_cleanlinesslevel_range_1_size_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lablog',
            name='items',
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='range_1_size_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='range_2_size_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='range_3_size_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='range_4_size_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='range_5_size_limit',
            field=models.IntegerField(),
        ),
    ]
