# Generated by Django 4.2.7 on 2023-11-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_lablog_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubblepointlog',
            name='mars_id',
        ),
    ]
