# Generated by Django 4.2.7 on 2023-11-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_bubblepointlog_mars_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubblepointlog',
            name='mars_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
