# Generated by Django 4.2.7 on 2023-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_item_images_item_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_image',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer_logos/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
