# Generated by Django 4.2.7 on 2023-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_manufacturer_manufacturer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='cleanliness_level_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cleanlinesslevel',
            name='standard',
            field=models.CharField(max_length=255),
        ),
    ]
