# Generated by Django 4.2.7 on 2023-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_location_status_workorder_location_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
