# Generated by Django 4.2.7 on 2023-11-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_workorder_location_alter_workorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('fitting_id', models.AutoField(primary_key=True, serialize=False)),
                ('fitting_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('lot_number', models.IntegerField()),
                ('fitting_size', models.CharField(max_length=50)),
                ('alternate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fitting')),
                ('cleanliness_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cleanlinesslevel')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderFitting',
            fields=[
                ('work_order_fitting_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.workorder')),
                ('work_order_unique_fitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fitting')),
            ],
        ),
        migrations.CreateModel(
            name='LabLogFitting',
            fields=[
                ('lab_log_fitting_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('lab_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.workorder')),
                ('lab_log_unique_fitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fitting')),
            ],
        ),
    ]
