# Generated by Django 4.2.7 on 2023-11-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_fitting_workorderfitting_lablogfitting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingSize',
            fields=[
                ('fitting_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='fitting',
            name='cleanliness_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cleanlinesslevel'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='fitting_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fittingsize'),
        ),
    ]
