# Generated by Django 4.2.7 on 2024-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_fittingsize_alter_fitting_cleanliness_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=500)),
                ('point_of_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fitting',
            name='cleanliness_level',
        ),
    ]
