# Generated by Django 4.2.7 on 2024-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_customer_remove_fitting_cleanliness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=-2747, max_length=15),
            preserve_default=False,
        ),
    ]
