# Generated by Django 4.2.7 on 2024-03-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_workorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cleanliness_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.cleanlinesslevel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.manufacturer'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='contaminant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.contaminant'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='damage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.damage'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
    ]
