# Generated by Django 4.2.7 on 2024-03-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_item_clean_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lablogfitting',
            name='lab_log_work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.workorder'),
        ),
        migrations.AddField(
            model_name='lablogitem',
            name='lab_log_work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.workorder'),
        ),
        migrations.AlterField(
            model_name='lablogfitting',
            name='lab_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lablog'),
        ),
    ]
