# Generated by Django 4.2.7 on 2024-03-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_lablogfitting_lab_log_work_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lablogfitting',
            name='lab_log_work_order',
        ),
        migrations.RemoveField(
            model_name='lablogitem',
            name='lab_log_work_order',
        ),
    ]
