# Generated by Django 4.2.7 on 2024-03-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_lablogfitting_lab_log_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lablog',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.workorder'),
        ),
    ]
