# Generated by Django 4.2.7 on 2024-03-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_lablog_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitting',
            name='alternate',
        ),
    ]
